name: Deploy to Server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_REGISTRY_URL }}
        username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ vars.DOCKER_REGISTRY_URL }}/funds-frontend:latest

    - name: Execute remote SSH cloudflared tunnel commands (rebuild)
      uses: npgy/cloudflared-ssh-action@v2.0
      with:    
        host: ${{ vars.SSH_IP }}
        username: ${{ vars.SSH_USERNAME }}
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ vars.SSH_PORT }}
        commands: |
          cd /srv/funds-backend && docker pull ${{ vars.DOCKER_REGISTRY_URL }}/funds-frontend:latest && docker-compose up -d frontend